### ISSUE TITLE
Automatically abort installation when volume keys aren't pressed after a timeout

### ISSUE THREAD

**Issue by MarcAnt01** [Zackptg5/Unity-Addons#4]
This will be useful for users whose volume keys aren't working and when Magisk manager freezes preventing users from choosing vol key options

**Comment by Zackptg5** [comment]
I'll look into this. Timeout was finicky when I tried it before but I've learned a lot since then so we'll see what happens this go around ;)

**Comment by Zackptg5** [comment]
Done :)
See Commit 7513975eeda95524709d77d6767f52bfe64b2502
